"""Add status to Lead model

Revision ID: 051c90481113
Revises: ea841704db97
Create Date: 2025-12-13 18:23:18.139115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051c90481113'
down_revision = 'ea841704db97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='New'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
