"""Manual migration for Lead model

Revision ID: b18bf7e36418
Revises:
Create Date: 2025-12-11 14:10:46.326612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18bf7e36418'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('telegram_user_id', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('activity_score', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('uq_lead_telegram_user_id', ['telegram_user_id'])
        batch_op.drop_column('review_text')
        batch_op.drop_column('customer_name')
        batch_op.drop_column('sentiment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentiment', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('customer_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('review_text', sa.TEXT(), nullable=False))
        batch_op.drop_constraint('uq_lead_telegram_user_id', type_='unique')
        batch_op.drop_column('activity_score')
        batch_op.drop_column('username')
        batch_op.drop_column('telegram_user_id')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
