"""Add sentiment and summary to Trend model

Revision ID: ea841704db97
Revises: 70f9b205ed3c
Create Date: 2025-12-13 14:09:22.914160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea841704db97'
down_revision = '70f9b205ed3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trend', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentiment', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trend', schema=None) as batch_op:
        batch_op.drop_column('summary')
        batch_op.drop_column('sentiment')

    # ### end Alembic commands ###
